apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: vuy3s5c5g-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-6b6352e682.243h.p3.openshiftapps.com/rhtap/rhtap-qe-dotnet-basic:b4af42c48545e79e3fcba42531cef7fe4d4d034a@sha256:8fc6a20b147f8c59bf1b1953d3b42a1f3e91a56d5e9f16f4ef911743a1f78f74
          name: container-image
